# Generated by Django 3.0.2 on 2020-01-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("price_currency", models.CharField(max_length=3)),
            ],
        ),
    ]
