# Generated by Django 3.0.2 on 2020-01-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
